// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaxhecpwubvknpzegpyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlheGhlY3B3dWJ2a25wemVncHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODI3NTksImV4cCI6MjA2NDM1ODc1OX0.k-Lv8O-O1FkukCaqpNRjjtD159OTusuj_7rm7g1yXaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);